### ISSUE TITLE
Themes are not available

### ISSUE THREAD

**Issue by akash-nx** [sphinx-themes/sphinx-themes.org#113]
Most of themes are not available and shows build failed. Also, I am trying to install book & furo theme but unable to do so. Ia m getting`pip install sphinx-book-theme
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement sphinx-book-theme (from versions: none)
ERROR: No matching distribution found for sphinx-book-theme`

**Comment by pradyunsg** [comment]
@akash-nx You're using Python 2, which is not supported since 2020. That's why you're seeing issues. Use a newer version of Python, otherwise ask whomever you're getting Python 2 from, for help with it. 

@humitos Those are themes being broken with Sphinx 6 (part of the goal with this site was to have it automatically test Sphinx pre-releases across themes). It's mildly concerning that alabaster is failing with Sphinx 6. :)

**Comment by akash-nx** [comment]
@pradyunsg  yes, I switched to python3 and resolved first issue. I wanted to try more themes but as you mentioned that its being tested with sphinx 6 so I will wait till all themes gets stable.
