### ISSUE TITLE
Suggestion for a theme

### ISSUE THREAD

**Issue by bitvijays** [sphinx-themes/sphinx-themes.org#82]
Dear Sphinx Themes Team,

Hope you are doing well. Thank you for your supporting and maintaining sphinx-themes. I was wondering if you are aware of any themes which allows full width content display and the contents display like gitbook. Here's a image to provide an instance.  We want to utilise the space on the both sides (marked in red). 

Thank you,
Yours Sincerely,
bitvijays

![image](https://user-images.githubusercontent.com/9039339/124358536-af1a6300-dc18-11eb-8ec8-dd7ec904fabf.png)

**Comment by pradyunsg** [comment]
There's no central theme development team for Sphinx, and all of the themes for Sphinx are developed by different groups of maintainers. What you see in https://sphinx-themes.org/ is the default configuration for basically all the reusable open source Sphinx themes that I know of.

There's a few themes that do what you seem to be asking for; however for the rest of them, I do doubt that they'd support this since the web design guidelines all recommend to limit the main content width (especially for prose, which is what most Sphinx documentation would be). Some references for these design guidelines:

- [W3's Best practices for line width and accessibility](https://www.w3.org/WAI/tutorials/page-structure/styling/#:~:text=Line%20length,characters%20or%20less%20are%20shown) and [this criterion page from W3C as well](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-visual-presentation.html)
- [Visual design guide from accessibility.digital.gov](https://accessibility.digital.gov/visual-design/typography/)
- [wikipedia page discussing their intent to cap the line width](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/Limiting_content_width#Goals_and_Motivation)
- [the Tufte CSS page](https://edwardtufte.github.io/tufte-css/)
  - a max-width of 1400px for all content, and then sets 55% for the main text and 45% for the sidebar text.
  - Main content: 55% of full width. Roughly 85 characters per line. Font size 1.4rem
  - Margin content: 50% of width of the main content. Roughly 60 characters per line. Font size 1.1rem
- [webtypography](http://webtypography.net/2.1.2) recommends about 66 characters per line

None the less, if you can't find what you're looking for -- there isn't much more I can help you with here, to be honest. Your best bet in that case would be to develop your own Sphinx theme that satifies your needs.

**Comment by bitvijays** [comment]
Thank you @pradyunsg That's really very helpful 👍
